export const TODOS_TYPES = {
    MY_TODOS: 'MY_TODOS',
    TODOS_CREATE: 'TODOS_CREATE',
    TODOS_EDIT: 'TODOS_EDIT',
    TODOS_DELETE: 'TODOS_DELETE'
}

export const USER_TYPES = {
    USER_SIGNIN: 'USER_SIGNIN',
    USER_SIGNUP: 'USER_SIGNUP',
}
